# Generated by Django 6.1 on 2026-08-26 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rezervim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emri', models.CharField(max_length=120)),
                ('telefoni', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('sherbimi', models.CharField(choices=[('kontroll', 'Kontroll & Higjienizim'), ('zbardhim', 'Zbardhim Dentar'), ('implant', 'Implantologji'), ('ortodonci', 'Ortodonci'), ('femije', 'Stomatologji Fëmijësh'), ('tjeter', 'Tjetër')], max_length=20)),
                ('data', models.DateField()),
                ('ora', models.CharField(blank=True, choices=[('', 'Nuk kam preferencë'), ('mengjes', '09:00 – 12:00'), ('dite', '12:00 – 16:00'), ('pasdite', '16:00 – 19:00')], max_length=20)),
                ('mesazhi', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('e_re', 'E re'), ('konfirmuar', 'Konfirmuar'), ('anulluar', 'Anulluar'), ('perfunduar', 'Përfunduar')], default='e_re', max_length=20)),
                ('krijuar_me', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-krijuar_me'],
            },
        ),
    ]
