# Generated by Django 6.1 on 2026-08-27 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezervime', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_slug', models.SlugField(blank=True, null=True, unique=True)),
                ('service_name', models.CharField(blank=True, max_length=200, null=True)),
                ('service_description', models.TextField(blank=True, null=True)),
                ('service_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('service_svg', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
